<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.documind</groupId>
        <artifactId>documind-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>documind-search</artifactId>
    <packaging>pom</packaging>
    <description>DocuMind-AI 搜索模块</description>

    <modules>
        <module>documind-search-api</module>
        <module>documind-search-service</module>
        <module>documind-search-server</module>
    </modules>

</project>


